name: sedtrails

channels:
  - conda-forge
  
dependencies:
  - python=3.13
  - numpy<2.2,>=1.24
  - numba
  - pandas
  - matplotlib
  - xarray
  - typer>=0.15.0,<1.0
  - pytest
  - flake8
  - sphinx=8.2.0
  - myst-parser=4.0.1
  - sphinx-rtd-theme
  - pyyaml
  - jsonschema
  - xugrid
  - tqdm
  - referencing>=0.36.2
  - pip:
    - sphinx-autodoc2>=0.5.0
  