general:
  input_model: 
    format: "fm_netcdf"
    reference_date: "1970-01-01"  # Default reference date for the input model
folder_settings:
  input_data: "./sample-data/inlet_sedtrails.nc"
  output_dir: "./results"
time:
  timestep: '30S'
  duration: '6H18M18S'
particles:
  sand:
    grain_size: 0.0005
particle_seeding:
  release_start: '2025-06-18 13:00:00'
  particles_per_timestep: 1.
  # TODO: provide a config template with all defaults
  strategy: 
    point:
      points: 
        - "40000,17000"
output:
  store_tracks: true
visualization:
  plotting:
    point_size: 7.0
