general:
  input_model: 
    format: fm_netcdf
    reference_date: 1970-01-01  # Default reference date for the input model
folder_settings:
  input_data: ./sample-data/dfm_sedtrails.nc
  output_dir: ./results
time:
  timestep: 30S
  duration: 6H18M18S
  start: 2011-08-01 00:00:00
particles:
  population:
    name: my_population
    particle_type: sand
    characteristics:
      grain_size: 0.00025 
      density: 2650.0  
    tracer_methods:
      vanwesten:
        alpha: 0.2
        beta: 0.3
    seeding:
      release_start: 2011-08-01 00:00:00
      quantity: 1
      strategy: 
        point:
          locations: 
            - "40000,17000"
output:
  store_tracks: true

