general:
  input_model: 
    format: fm_netcdf
    reference_date: 1970-01-01  # Default reference date for the input model
folder_settings:
  input_data: ./sample-data/dfm_sedtrails.nc
  output_dir: ./results
time:
  start: 2011-08-01 00:00:00
  timestep: PT30S      # ISO 8601: 30 seconds
  read_input_timestep: PT1M    # ISO 8601: 1 minute
particles:
  population:
    name: my_population
    particle_type: sand
    characteristics:
      grain_size: 0.00025 
      density: 2650.0  
    tracer_methods:
      vanwesten:
        alpha: 0.2
        beta: 0.3
    seeding:
      release_start: 2011-08-01 00:00:00
      quantity: 1
      strategy: 
        point:
          locations: 
            - "40000,17000"
output:
  store_tracks: true

# ISO 8601 Duration Format Examples:
#   PT30S              # 30 seconds
#   PT1M               # 1 minute  
#   PT1H               # 1 hour
#   P1D                # 1 day
#   P1Y                # 1 year
#   P1M                # 1 month
#   P1Y6M              # 1 year, 6 months
#   P1Y6M15D           # 1 year, 6 months, 15 days
#   P1Y6M15DT12H25M30S # 1 year, 6 months, 15 days, 12 hours, 25 minutes, 30 seconds
#   P3DT2H1M3S         # 3 days, 2 hours, 1 minute, 3 seconds
#   PT12H              # 12 hours (time-only duration)