name: Pytest

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  unit:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python3.13-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-python3.13-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install the package with dev dependencies
        pip install -e ".[dev]"
        pip list | grep typer
        
    - name: Run pytest
      run: |
        pytest tests/ -v --tb=short -m "not integration"

  integration:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: unit

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python3.13-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-python3.13-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip list | grep typer

    - name: Run integration tests only
      run: |
        pytest tests/ -v --tb=short -m integration